
import requests
import time
import os
import json

API_URL = "http://localhost:8000"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def verify_chat_task():
    print("Verifying Chat-to-Task Execution...")

    # 1. Get/Create Assistant Agent
    print("\n[1] Getting Assistant Agent...")
    res = requests.get(f"{API_URL}/agents/")
    agents = res.json()
    sarah = next((a for a in agents if a['name'] == "Sarah_Assistant"), None)
    
    if not sarah:
        print("Sarah_Assistant not found. Please run verify_assistant.py first.")
        # Create it if missing
        agent_data = {
            "name": "Sarah_Assistant",
            "role": "General Assistant",
            "job_title": "Executive Assistant",
            "department": "Admin",
            "level": "Staff",
            "system_prompt": "You are a helpful assistant."
        }
        res = requests.post(f"{API_URL}/agents/", json=agent_data)
        sarah = res.json()
        
    print(f"Agent ID: {sarah['id']}")

    # 2. Simulate Chat Flow
    # We will simulate the *Confirmation* step directly by simulating the user saying "Yes, execute it."
    # We cheat a bit by asking the agent to explicitly output the tag to test the parsing logic.
    print("\n[2] Triggering Task Execution via Chat...")
    
    prompt = (
        "I confirm. Please generate a file named 'Test_Report.md' with the content 'This is a test report generated via chat.' "
        "Remember to use the [[EXECUTE_TASK: ...]] tag."
    )
    
    chat_payload = {
        "agent_id": sarah['id'],
        "message": prompt
    }
    
    res = requests.post(f"{API_URL}/chat/", json=chat_payload, stream=True)
    full_resp = ""
    for chunk in res.iter_content(chunk_size=None):
        if chunk:
            full_resp += chunk.decode('utf-8')
            
    print("Agent Response:", full_resp)
    
    if "[[EXECUTE_TASK:" in full_resp:
        print("SUCCESS: Tag generated by Agent.")
    else:
        print("WARNING: Tag NOT generated. Parsing logic won't trigger.")
        
    # 3. Verify Task Creation & File
    print("\n[3] Waiting for Background Task...")
    time.sleep(5) # Give it some time
    
    # Check Tasks
    res = requests.get(f"{API_URL}/tasks/?limit=5")
    tasks = res.json()
    # Look for our task
    found_task = next((t for t in tasks if "Test_Report" in t['title'] or "Test Report" in t['title']), None)
    
    if found_task:
        print(f"SUCCESS: Task found: {found_task['title']} (Status: {found_task['status']})")
        
        # Check File
        # Expected path: Company Doc/Sarah_Assistant/...
        agent_name_clean = "Sarah_Assistant" # Simplified
        search_dir = os.path.join(BASE_DIR, "Company Doc", agent_name_clean)
        
        if os.path.exists(search_dir):
            files = os.listdir(search_dir)
            # Look for recent file
            matching_files = [f for f in files if "Test_Report" in f or "Test_Report" in f]
            if matching_files:
                print(f"SUCCESS: File created: {matching_files[0]}")
            else:
                print(f"FAILURE: Task exists but file not found in {search_dir}")
                print(f"Existing files: {files}")
        else:
            print(f"FAILURE: Directory {search_dir} does not exist.")
            
    else:
        print("FAILURE: Task was not created in DB.")
        print("Recent tasks:", [t['title'] for t in tasks])

if __name__ == "__main__":
    verify_chat_task()
